### PR TITLE
first stab at sphinx docs

### PR DESCRIPTION
**Pull request by christopherpickering**
also added 
- application factory example
- tox file

### CODE REVIEW

**Comment by christopherpickering** [comment]
To turn the pages on, I think you can go in settings:
image

**Comment by christopherpickering** [comment]
thanks! In the settings what link does it give you for the pages when it turns on? I can update the readme to the correct link if I guessed wrong :)

**Comment by viniciuschiele** [comment]
It looks great https://viniciuschiele.github.io/flask-apscheduler

**Comment by christopherpickering** [comment]
nice!! thanks!

**Comment by kmcmearty** [comment]
@christopherpickering thank you for the awesome flask factory pattern example!

**Comment by christopherpickering** [comment]
Thanks! Here's a link to the site we use it one if you can use more examples!
https://github.com/Riverside-Healthcare/extract_management/tree/main/em_scheduler

**Pull request merged**
