### PR TITLE
added readme as long description for pypi

### PR DESCRIPTION
**Pull request by christopherpickering**

### CODE REVIEW

**Comment by christopherpickering** [comment]
I'm not sure why it lists all those changed files as they have already been merged into master.. the only one that should be listed in the merge is the ``setup.py`` changes.

**Comment by viniciuschiele** [comment]
hmm.. I guess this happened because in the previous PRs I used `Squash and Merge` to merge them into master.

Do you mind forking again this repo and push a new PR?

**Comment by christopherpickering** [comment]
yep, no problem!

**Comment by christopherpickering** [comment]
resubmitted.

**Pull request closed without merging**
