### PR TITLE
add endpoint_prefix, update api_prefix

### PR DESCRIPTION
**Pull request by andreicalistru**
- Added SCHEDULER_ENDPOINT_PREFIX
- updated SCHEDULRE_API_PREFIX
- set default values for SCHEDULER_ENDPOINT_PREFIX and SCHEDULER_API_PREFIX

### CODE REVIEW

**Comment by viniciuschiele** [comment]
Thanks for that.

Can you update the two unit tests around it, please?

**Comment by andreicalistru** [comment]
I updated most of the tests to match the api_prefix implementation

**Comment by andreicalistru** [comment]
I could try to write some tests for the endpoint_prefix as well.

**Comment by viniciuschiele** [comment]
Oops... I didn't see your last comment before merging it.

Yes, it would be great to have some unit tests around that.

Thanks

**Comment by andreicalistru** [comment]
I just did a new PR for that, let me know when you update the PYPI repo so that I can pull the new package ;)
Thanks!

**Comment by viniciuschiele** [comment]
I've added a new method **_add_url_route** to keep things simpler

**Pull request merged**
