### PR TITLE
Changes:

### PR DESCRIPTION
**Pull request by eayin2**
- In job definitions and apscheduler methods: `job_id` instead of `id`.
- Invoking scheduler.start() within init_app(), because jobs are modified within init_app() (to update possible job
  definition changes to the existing jobstore jobs). Before modifying any jobs the scheduler has to be started.
- REST API extended with reschedule_job, reschedule_job_once and reload_jobs.

### CODE REVIEW

**Comment by viniciuschiele** [comment]
Hi @eayin2 

Your pull request has many errors like missing variables, all unit tests fail.

Some observations:

**In job definitions and apscheduler methods: job_id instead of id.**
We cannot rename this field, it will break compatibility with previous versions and APScheduler also expect a parameter **id** rather than **job_id**

**Invoking scheduler.start() within init_app(), because jobs are modified within init_app() (to update possible job definition changes to the existing jobstore jobs). Before modifying any jobs the scheduler has to be started.**
It seems you have jobs in your jobstore (possibly a DB job store) and you also have jobs in your config file, I don't think that is a good idea, you should keep all your jobs in only one place. Could you tell me why are you doing it?

**REST API extended with reschedule_job, reschedule_job_once and reload_jobs.**
I like those APIs, I may consider including them

Cheers!

**Comment by eayin2** [comment]
Hey Vinicius,

apscheduler.job.Job() uses indeed id for the job id. I noticed that the methods modify_job, reschedule_job, pause_job, resume_job, get_job and remove_job from apscheduler.schedulers use job_id, so it was more convenient to use **job_id** (considering we mainly work with the scheduler), yet i just noticed that schedulers.add_job() actually uses **id**, thus i agree it's better to use **id** overall.

I keep my jobs in the jobstore so that they persist when the scheduler process is down. For jobs that have to run for example only once every 3 months it is important, else they'd be rescheduled another 3 months if the scheduler process is down. My goal with reload_jobs() is that the jobstore can receive job definition updates on startup and through flask-apscheduler's REST API.

Cheers! :)

**Comment by viniciuschiele** [comment]
I don't think reload_jobs and reschedule_job_once should receive a file path to update the job.

About starting the scheduler automatically before loading the jobs, it's a breaking change because everybody calls .start() manually and if it is already started it will raise an error.

Maybe we could add a new config variable to enable or disable the auto start and the start method could check if the scheduler is already running and do not raise an error if so.

I need to think further about that.

**Comment by eayin2** [comment]
Ah right, to not people's code then it might be better to put self.reload_jobs(jobs=jobs) to flask_apscheduler.APScheduler.start, right after self.__scheduler.start() and not in init_app().

**I don't think reload_jobs and reschedule_job_once should receive a file path to update the job.**
Yea, I didn't like this either. For reschedule_job_once() it could be workaround to simply pull the job defintions priorly with get_job(). 
reload_jobs doesn't need the config path on first run (gets it via jobs parameter instead), but
when invoking reload_jobs from the REST API it needs to know where the config file is to apply possible changes to the jobstore. The configpath could be provided via flask config class "Config()" too, but then the REST API should also allow to change the configpath afterwards, considering the config path may change.

**Comment by eayin2** [comment]
> I don't think reload_jobs and reschedule_job_once should receive a file path to update the job.
I removed the file path from the REST API. Now you can simply add the path to the config. This is also securer, because an attacker can now no more have it run any jobs he wanted to.

### Example
SCHEDULER_JOBCONFIG = "some_module.settings.jobs"

#### some_module.settings.py
jobs = [
    {
        "id": "daily",
        "func": "some_module.some_file:some_reference",
        "trigger": some_interval
    }
]

**Pull request closed without merging**
