### PR TITLE
added tests and workflow

### PR DESCRIPTION
**Pull request by christopherpickering**
- added tests to increase cov to 96%
- added demo workflow for sphinx docs

### CODE REVIEW

**Comment by christopherpickering** [comment]
image

**Comment by viniciuschiele** [comment]
Thanks for the help on that front

**Comment by viniciuschiele** [comment]
The workflow has failed, would you know why?

**Comment by christopherpickering** [comment]
Yes, I didn't put any config in for sphinx. I'll give it a shot this week, thanks for merging.

I will try to put the basic flask example, and the application factory examples from the other chats in there.

**Pull request merged**
